name: Build and Push Image to Github Container Registry

on:
  [workflow_dispatch]
  # pull_request:
  #   branches: [ "staging" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 0xsimbadev/gilliozdreamlabs

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        github-token: ${{ secrets.DOCKER_PASSWORD }}
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,format=short
          type=ref,event=tag
          type=ref,event=branch,prefix=latest
    
    - name: Access Metadata
      run: |
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo "Labels: ${{ steps.meta.outputs.labels }}"